const TwitterStatsDb = "TwitterStats"

const statsCollection = "stats";

const header = `"Tweet id","Tweet permalink","Tweet text","time","impressions","engagements","engagement rate","retweets","replies","likes","user profile clicks","url clicks","hashtag clicks","detail expands","permalink clicks","app opens","app installs","follows","email tweet","dial phone","media views","media engagements","promoted impressions","promoted engagements","promoted engagement rate","promoted retweets","promoted replies","promoted likes","promoted user profile clicks","promoted url clicks","promoted hashtag clicks","promoted detail expands","promoted permalink clicks","promoted app opens","promoted app installs","promoted follows","promoted email tweet","promoted dial phone","promoted media views","promoted media engagements"`;

const validTweetId = "1226928883355791360"

const validTweetCsv = `"${validTweetId}","https://twitter.com/Lauren_Schaefer/status/${validTweetId}","Simple tweet","2020-02-10 18:00 +0000","1203.0","39.0","0.032418952618453865","4.0","0.0","7.0","2.0","22.0","0.0","4.0","0.0","0","0","0","0","0","0","0","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"`;

const validTweetJson = {
    "Tweet permalink": "https://twitter.com/Lauren_Schaefer/status/" + validTweetId,
    "Tweet text": "Simple tweet",
    "_id": validTweetId,
    "app installs": 0,
    "app opens": 0,
    "author": "Lauren_Schaefer",
    "date": new Date("2020-02-10 00:00 +0000"),
    "detail expands": 4,
    "dial phone": 0,
    "email tweet": 0,
    "engagement rate": 0.032418952618453865,
    "engagements": 39,
    "follows": 0,
    "hashtag clicks": 0,
    "impressions": 1203,
    "likes": 7,
    "media engagements": 0,
    "media views": 0,
    "permalink clicks": 0,
    "promoted app installs": "-",
    "promoted app opens": "-",
    "promoted detail expands": "-",
    "promoted dial phone": "-",
    "promoted email tweet": "-",
    "promoted engagement rate": "-",
    "promoted engagements": "-",
    "promoted follows": "-",
    "promoted hashtag clicks": "-",
    "promoted impressions": "-",
    "promoted likes": "-",
    "promoted media engagements": "-",
    "promoted media views": "-",
    "promoted permalink clicks": "-",
    "promoted replies": "-",
    "promoted retweets": "-",
    "promoted url clicks": "-",
    "promoted user profile clicks": "-",
    "replies": 0,
    "retweets": 4,
    "time": "2020-02-10 18:00 +0000",
    "url clicks": 22,
    "user profile clicks": 2
};

const validTweetUpdatedCsv = `"${validTweetId}","https://twitter.com/Lauren_Schaefer/status/${validTweetId}","Simple tweet","2020-02-10 18:00 +0000","1423.0","45.0","0.05134498689","6.0","1.0","10.0","3.0","26.0","0.0","0","3.0","0","0","3.0","0","0","0","0","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"`;

const validTweetUpdatedJson = {
    "Tweet permalink": "https://twitter.com/Lauren_Schaefer/status/" + validTweetId,
    "Tweet text": "Simple tweet",
    "_id": validTweetId,
    "app installs": 0,
    "app opens": 0,
    "author": "Lauren_Schaefer",
    "date": new Date("2020-02-10 00:00 +0000"),
    "detail expands": 0,
    "dial phone": 0,
    "email tweet": 0,
    "engagement rate": 0.05134498689,
    "engagements": 45,
    "follows": 3,
    "hashtag clicks": 0,
    "impressions": 1423,
    "likes": 10,
    "media engagements": 0,
    "media views": 0,
    "permalink clicks": 3,
    "promoted app installs": "-",
    "promoted app opens": "-",
    "promoted detail expands": "-",
    "promoted dial phone": "-",
    "promoted email tweet": "-",
    "promoted engagement rate": "-",
    "promoted engagements": "-",
    "promoted follows": "-",
    "promoted hashtag clicks": "-",
    "promoted impressions": "-",
    "promoted likes": "-",
    "promoted media engagements": "-",
    "promoted media views": "-",
    "promoted permalink clicks": "-",
    "promoted replies": "-",
    "promoted retweets": "-",
    "promoted url clicks": "-",
    "promoted user profile clicks": "-",
    "replies": 1,
    "retweets": 6,
    "time": "2020-02-10 18:00 +0000",
    "url clicks": 26,
    "user profile clicks": 3
};

const emojiTweetId = "1226928883355791361";

const emojiTweetCsv = `"${emojiTweetId}","https://twitter.com/Lauren_Schaefer/status/${emojiTweetId}","Emoji tweet 😀💅👸","2020-02-11 18:00 +0000","1203.0","39.0","0.032418952618453865","4.0","0.0","7.0","2.0","22.0","0.0","4.0","0.0","0","0","0","0","0","0","0","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"`;

const emojiTweetJson = {
    "Tweet permalink": "https://twitter.com/Lauren_Schaefer/status/" + emojiTweetId,
    "Tweet text": "Emoji tweet ",
    "_id": emojiTweetId,
    "app installs": 0,
    "app opens": 0,
    "author": "Lauren_Schaefer",
    "date": new Date("2020-02-11 00:00 +0000"),
    "detail expands": 4,
    "dial phone": 0,
    "email tweet": 0,
    "engagement rate": 0.032418952618453865,
    "engagements": 39,
    "follows": 0,
    "hashtag clicks": 0,
    "impressions": 1203,
    "likes": 7,
    "media engagements": 0,
    "media views": 0,
    "permalink clicks": 0,
    "promoted app installs": "-",
    "promoted app opens": "-",
    "promoted detail expands": "-",
    "promoted dial phone": "-",
    "promoted email tweet": "-",
    "promoted engagement rate": "-",
    "promoted engagements": "-",
    "promoted follows": "-",
    "promoted hashtag clicks": "-",
    "promoted impressions": "-",
    "promoted likes": "-",
    "promoted media engagements": "-",
    "promoted media views": "-",
    "promoted permalink clicks": "-",
    "promoted replies": "-",
    "promoted retweets": "-",
    "promoted url clicks": "-",
    "promoted user profile clicks": "-",
    "replies": 0,
    "retweets": 4,
    "time": "2020-02-11 18:00 +0000",
    "url clicks": 22,
    "user profile clicks": 2
};

const validTweetKenId = "1226928883355791362"

const validTweetKenCsv = `"${validTweetKenId}","https://twitter.com/kenwalger/status/${validTweetKenId}","I like to make bad dad jokes","2020-02-12 18:00 +0000","10005.0","62.0","0.041111111111111","5.0","3.0","33.0","5.0","62.0","0.0","11.0","3.0","0","0","3.0","0","0","0","0","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"`;

const validTweetKenJson = {
    "Tweet permalink": "https://twitter.com/kenwalger/status/" + validTweetKenId,
    "Tweet text": "I like to make bad dad jokes",
    "_id": validTweetKenId,
    "app installs": 0,
    "app opens": 0,
    "author": "kenwalger",
    "date": new Date("2020-02-12 00:00 +0000"),
    "detail expands": 11,
    "dial phone": 0,
    "email tweet": 0,
    "engagement rate": 0.041111111111111,
    "engagements": 62,
    "follows": 3,
    "hashtag clicks": 0,
    "impressions": 10005,
    "likes": 33,
    "media engagements": 0,
    "media views": 0,
    "permalink clicks": 3,
    "promoted app installs": "-",
    "promoted app opens": "-",
    "promoted detail expands": "-",
    "promoted dial phone": "-",
    "promoted email tweet": "-",
    "promoted engagement rate": "-",
    "promoted engagements": "-",
    "promoted follows": "-",
    "promoted hashtag clicks": "-",
    "promoted impressions": "-",
    "promoted likes": "-",
    "promoted media engagements": "-",
    "promoted media views": "-",
    "promoted permalink clicks": "-",
    "promoted replies": "-",
    "promoted retweets": "-",
    "promoted url clicks": "-",
    "promoted user profile clicks": "-",
    "replies": 3,
    "retweets": 5,
    "time": "2020-02-12 18:00 +0000",
    "url clicks": 62,
    "user profile clicks": 5
};

module.exports = {
    TwitterStatsDb,
    statsCollection,
    header,
    validTweetId,
    validTweetCsv,
    validTweetJson,
    validTweetUpdatedCsv,
    validTweetUpdatedJson,
    emojiTweetId,
    emojiTweetCsv,
    emojiTweetJson,
    validTweetKenId,
    validTweetKenCsv,
    validTweetKenJson
};